server:
  port: 8200
  
spring:
  application:
    name: convertcurrency
  zipkin:
    base-url: http://localhost:9411/    
  sleuth:
    sampler:
      probability: 1.0
    trace-id128: true
    
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      appname: ${spring.application.name}-${random.int}
             
management:
  endpoints:
    web:
      exposure:
        include: "*"     
