server:
  port: 8100
  
  
spring:  application:    name: currencyconversionfactor
  datasource:
    url: jdbc:h2:mem:conversionfactor
    driver-class-name: org.h2.Driver
    username: ibm
    password: ibm
  h2:
    console:
      enabled: true   
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
    trace-id128: true

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      appname: ${spring.application.name}-${random.int}
             
management:
  endpoints:
    web:
      exposure:
        include: "*"  
           