DROP TABLE IF EXISTS CURRENCYCONVFACTOR;  
CREATE TABLE CURRENCYCONVFACTOR (  
	ID NUMBER AUTO_INCREMENT  PRIMARY KEY,  
	COUNTRYCODE VARCHAR(10) NOT NULL,  
	CONVERSIONFACTOR DOUBLE NOT NULL  
);  
INSERT INTO CURRENCYCONVFACTOR (COUNTRYCODE, CONVERSIONFACTOR) VALUES ('USA', 73.6);  
INSERT INTO CURRENCYCONVFACTOR (COUNTRYCODE, CONVERSIONFACTOR) VALUES ('EUR', 86.037);  
INSERT INTO CURRENCYCONVFACTOR (COUNTRYCODE, CONVERSIONFACTOR) VALUES ('AUS', 52.5); 